### ISSUE TITLE
Epic 2: Develop - Convert to Use Axios

### ISSUE THREAD

**Issue by Sharu201101** [BitBytes-team/Project-6#4]
As a developer, I want the assignee to convert the Photo App to use Axios for fetching data instead of the FetchModel routine. This transition will help us prepare for the next assignment, improve data fetching efficiency, and ensure that the app functions as before without the FetchModel function. 

Aceeptance Criteria :  

- Replace all instances of FetchModel with axios.get for data fetching within photoShare.jsx and other components. 
- Import axios as import axios from 'axios'; in components where data is fetched. 
- Attach success and failure handlers to axios.get using .then and .catch to ensure proper data handling. 
- Ensure that the logic of the handlers, especially error handling, remains consistent with the previous FetchModel 
   functionality. 
- Verify that the app's functionality remains unchanged after the transition to Axios.

**Comment by ruchitha007** [comment]
import React from 'react';
import ReactDOM from 'react-dom';
import { BrowserRouter, Route, Switch } from 'react-router-dom';
import { Grid, Typography, Paper} from '@mui/material';
import './styles/main.css';

import TopBar from './components/topBar/TopBar';
import UserDetail from './components/userDetail/userDetail';
import UserList from './components/userList/userList';
import UserPhotos from './components/userPhotos/userPhotos';

class PhotoShare extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      topname: '',
    };
  }

  setTopName = (name) => {
    this.setState({ topname: name });
  };

  render() {  
    return (
      <BrowserRouter>
        <div>
          <Grid container spacing={8}>
            <Grid item xs={12}>
              <TopBar topName={this.state.topname} />
            </Grid>
            <div className="main-topbar-buffer" />
            <Grid item sm={2}>
              <Paper className="main-grid-item">
                <UserList setTopName={this.setTopName} />
              </Paper>
            </Grid>
            <Grid item sm={10}>
              
                <Switch>
                  <Route
                    exact
                    path="/"
                    render={() => (
                      <Typography variant="body1">
                        {/* Welcome to your photosharing app! This{' '}
                        <a href="https://mui.com/components/paper/">Paper</a> component
                        displays the main content of the application. The {'"sm={9}"'} prop in
                        the <a href="https://mui.com/components/grid/">Grid</a> item component makes it responsively
                        display 9/12 of the window. The Switch component enables us to conditionally render different
                        components to this part of the screen. You don't need to display anything here on the homepage,
                        so you should delete this Route component once you get started. */}
                      </Typography>
                    )}
                  />
                  <Route path="/users/:userId" component={UserDetail} />
                  <Route path="/photos/:userId" component={UserPhotos} />
                  <Route path="/users" component={UserList} />
                </Switch>
              
            </Grid>
          </Grid>
        </div>
      </BrowserRouter>
    );
  }
}
ReactDOM.render(<PhotoShare />, document.getElementById('photoshareapp'));


import React from 'react';
import { AppBar, Toolbar, Typography } from '@mui/material';
import './TopBar.css';
import axios from 'axios';
//import FetchModel from '../../lib/fetchModelData';

class TopBar extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      app_info: null,
    };
  }

  componentDidMount() {
    this.handleAppInfoChange();
  }

  handleAppInfoChange() {
    const app_info = this.state.app_info;
    if (app_info === null) {
      axios.get('/test/info')
          .then((response) => {
            this.setState({
              app_info: response.data,
            });
          })
          .catch((error) => {
            console.error('Error fetching app info:', error);
          });
    }
  }

  render() {
    const toolbarStyle = {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      width: '90%',
    };

    return (
        <AppBar className="topbar-appBar" position="absolute">
          <Toolbar style={toolbarStyle}>
            <Typography variant="h5" color="white">
              BITBYTES
            </Typography>
            <Typography variant="h6" color="white">
              {this.props.topName}
            </Typography>
            {this.state.app_info && (
                <Typography variant="h5" component="div" color="inherit">
                  Version: {this.state.app_info.version}
                </Typography>
            )}
          </Toolbar>
        </AppBar>
    );
  }
}
export default TopBar;

I've completed the development tasks for the Axios transition.  
FetchModel has been replaced with axios , get, and all handlers have been attached as needed.  
The app's functionality appears consistent. Ready for code review
